// Generated by Wrangler by running `wrangler types`

interface Env {
	NODE_VERSION: "22";
	PROJECT_ACCESS_KEY: string;
	WAAS_CONFIG_KEY: string;
	GOOGLE_CLIENT_ID: string;
	APPLE_CLIENT_ID: string;
	WALLET_CONNECT_ID: string;
}
